name: 'Application Health Check'
description: 'Argocd Application Health Check'
inputs:
  argocd-cli-version:
    description: 'argocd-cli-version'
    required: false
    default: 'v1.8.3'
  servername:
    description: 'argocd server endpoint'
    required: true
  username:
    description: 'argocd username'
    required: false
    default: 'admin'
  password:
    description: 'argocd password'
    required: true
  application:  # id of input
    description: 'Name of the application to Health check'
    required: true
  revision:
    description: 'Git commit revision'
    required: true
outputs:
  returncode:
    description: "Application Health Status"
    value: ${{ steps.health-check.outputs.status }}

runs:
  using: "composite"
  steps: 
    - id: install-argocd-cli
      run: ${{ github.action_path }}/install_argocd_cli.sh ${{ inputs.argocd-cli-version }}
      shell: bash
    - id: login
      run: /tmp/argocd --grpc-web login ${{ inputs.servername }} --username=${{ inputs.username }} --password=${{ inputs.password }}
      shell: bash
    - id: health-check
      run: echo "::set-output name=status::$(${{ github.action_path }}/healthcheck.sh ${{ inputs.application }} ${{ inputs.revision }})"
      shell: bash
